export const actionTypesRedux = {
  SET_POSTS: "SET_POSTS",
  SEARCH_POSTS: "SEARCH_POSTS",
  ADD_COMMENT: "ADD_COMMENT",
  ADD_REPLY: "ADD_REPLY",
  ADD_POST_TO_COLUMN: "ADD_POST_TO_COLUMN",
  REMOVE_POST_FROM_COLUMN: "REMOVE_POST_FROM_COLUMN",
  CHANGE_PAGE: "CHANGE_PAGE",
  CHANGE_POSTS_PER_PAGE: "CHANGE_POSTS_PER_PAGE",
};
